name: buoi06_btvn7
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Đọc tin nhắn SMS
  flutter_sms_inbox: ^1.0.3

  # Xin quyền READ_SMS
  permission_handler: ^12.0.1

  # Định dạng ngày giờ
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true